name: Build Test & Deploy

on:
  push:
    branches:
      - "staging"
      - "main"

jobs:
  build-test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Get branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: get_branch_name

      - name: "Checkout Latest Code ...."
        uses: actions/checkout@v2

      - name: "Setup NodeJs 12.x ...."
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: "Configure AWS CLI ...."
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: ${{secrets.AWS_REGION}}

      - name: "Create .env file...."
        run: |
          echo '
            REACT_APP_BRANCH_NAME= ${{ steps.get_branch_name.outputs.branch }}
          ' >> ./.env

      - name: "Insatll Yarn...."
        run: npm install -g yarn

      - name: "Install dependencies...."
        run: yarn install --frozen-lockfile

      - name: "Run Unit Test...."
        run: yarn test

      - name: "Build React APP...."
        run: yarn build

      - name: "AWS S3 Sync To APP Bucket...."
        run: aws s3 sync ./build s3://${{secrets.BUCKET_NAME}} --acl public-read

      - name: "AWS Cloud Front Create new invalidation...."
        run: aws cloudfront create-invalidation --distribution-id ${{secrets.DISTRIBUTION_ID}} --paths "/*"
