name: CI for React APP

on:
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout Latest Code ...."
        uses: actions/checkout@v2

      - name: "Setup NodeJs 12.x ...."
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: "Install dependencies...."
        uses: "yarn install"

      - name: "Run Unit Test...."
        uses: "yarn test"
