name: Build Test & Deploy

on:
  push:
    branches: [main]

jobs:
  build-test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout Latest Code ...."
        uses: actions/checkout@v2

      - name: "Setup NodeJs 12.x ...."
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: "Insatll Yarn...."
        run: npm install -g yarn

      - name: "Install dependencies...."
        run: yarn install

      - name: "Run Unit Test...."
        run: yarn test
